# Exported from Render

services:
  - type: web
    name: creata-bot
    runtime: python
    repo: https://github.com/uniqcreata/creata-bot
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: ALPHA_VANTAGE_KEY
        sync: false
    region: frankfurt
    autoDeploy: true

version: "1"
